"use client";

import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

import type { Locale, Numeric, Transaction } from "@/types";

function toNumber(value: Numeric | null | undefined) {
  if (value === null || value === undefined) {
    return 0;
  }

  const parsedValue =
    typeof value === "number" ? value : Number.parseFloat(value);

  return Number.isFinite(parsedValue) ? parsedValue : 0;
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-GB", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(new Date(value));
}

function formatAmount(value: Numeric, currency: Transaction["currency"]) {
  const amount = toNumber(value);

  if (currency === "USD") {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      maximumFractionDigits: 2,
    }).format(amount);
  }

  return `${new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 0,
  }).format(amount)} LBP`;
}

function getCategoryLabel(transaction: Transaction, locale: Locale) {
  if (!transaction.category) {
    return "-";
  }

  return locale === "ar"
    ? transaction.category.name_en
    : transaction.category.name_en;
}

function getStatusLabel(status: Transaction["status"]) {
  return status === "pending" ? "Needs review" : "Saved";
}

export function generateTransactionPDF(
  transactions: Transaction[],
  locale: Locale,
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const totalIncome = transactions.reduce((sum, transaction) => {
    if (transaction.category?.type !== "income") {
      return sum;
    }

    return sum + toNumber(transaction.usd_equivalent || transaction.amount);
  }, 0);

  const totalExpenses = transactions.reduce((sum, transaction) => {
    if (transaction.category?.type !== "expense") {
      return sum;
    }

    return sum + toNumber(transaction.usd_equivalent || transaction.amount);
  }, 0);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("LiraTrack - Transaction History", 297.5, 40, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Exported on ${formatDate(new Date().toISOString())}`, 40, 68);
  doc.text(
    `Total Income: $${totalIncome.toFixed(2)} | Total Expenses: $${totalExpenses.toFixed(2)}`,
    40,
    86,
  );

  autoTable(doc, {
    startY: 104,
    head: [["Date", "Description", "Category", "Amount", "Currency", "Status"]],
    body: transactions.map((transaction) => [
      formatDate(transaction.transaction_date),
      transaction.description || "-",
      getCategoryLabel(transaction, locale),
      formatAmount(transaction.amount, transaction.currency),
      transaction.currency,
      getStatusLabel(transaction.status),
    ]),
    theme: "striped",
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 8,
      textColor: [31, 41, 55],
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
    },
    headStyles: {
      fillColor: [30, 64, 175],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    bodyStyles: {
      fillColor: [255, 255, 255],
    },
    margin: {
      top: 104,
      right: 40,
      bottom: 52,
      left: 40,
    },
    didDrawPage: () => {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by LiraTrack", 297.5, 820, { align: "center" });
    },
  });

  doc.save("LiraTrack_History.pdf");
}
